SENTENCE_TEMPLATE = [
    "The [scene type] showcases [objects in the image and their quantity] amidst [lighting condition] during [time and weather conditions].",
    "[time and weather conditions] magnify the beauty of [scene type], focusing on [objects in the image and their quantity] captured at different [lighting condition].",
    "Visible in [lighting condition], [objects in the image and their quantity] meld seamlessly into the [scene type] during [time and weather conditions].",
    "A dazzling [scene type], opportunely captured in [lighting condition], features [objects in the image and their quantity] at [time and weather conditions].",
    "There's a [scene type] under [time and weather conditions] with [objects in the image and their quantity] being highlighted in the [lighting condition].",
    "The [scene type] unfolds, revealing [objects in the image and their quantity] under [lighting condition] during [time and weather conditions].",
    "Against a backdrop of [time and weather conditions], [objects in the image and their quantity] emerge prominently on the [scene type] with [lighting condition].",
    "Gleaming under [lighting condition], [objects in the image and their quantity] standout amidst the [scene type] set during [time and weather conditions].",
    "The [scene type] is bathed in [lighting condition], spotlighting [objects in the image and their quantity] during a typical [time and weather conditions].",
    "[time and weather conditions] inevitably add charm to [scene type], illuminating [objects in the image and their quantity] under [lighting condition].",
    "The [scene type] under [lighting condition] accentuates [objects in the image and their quantity] amidst [time and weather conditions].",
    "During [time and weather conditions], the [scene type] with [lighting condition] showcases [objects in the image and their quantity].",
    "The [scene type] delivers a vivid picture of [objects in the image and their quantity] in [lighting condition] during [time and weather conditions].",
    "Captured during [time and weather conditions], the [scene type] focuses attention on [objects in the image and their quantity] under the [lighting condition].",
    "The [scene type] is brought to life, spotlighting [objects in the image and their quantity] under [lighting condition] spotlight during [time and weather conditions].",
    "The [scene type] is alive with [objects in the image and their quantity] amidst the [lighting condition] during [time and weather conditions].",
    "An evocative [scene type] captures [objects in the image and their quantity] under [lighting condition] during [time and weather conditions].",
    "The [scene type] under [lighting condition] draws focus to [objects in the image and their quantity] despite of [time and weather conditions].",
    "Featuring [objects in the image and their quantity], the [scene type] is superbly depicted under [lighting condition] during [time and weather conditions].",
    "The [scene type] appears vivid, illustrating the sight of [objects in the image and their quantity] amidst [lighting condition] during [time and weather conditions].",
    "The [scene type] in [lighting condition], displaying [objects in the image and their quantity], perfectly describes the situation during [time and weather conditions].",
    "Given the [time and weather conditions], the fascinating [scene type] presents [objects in the image and their quantity] under [lighting condition].",
    "The [lighting condition] sets an enchanting mood for the [scene type] capturing [objects in the image and their quantity] during [time and weather conditions].",
    "In this [scene type], the [lighting condition] portrays [objects in the image and their quantity] against the backdrop of [time and weather conditions].",
    "The [scene type] reflects [objects in the image and their quantity] set within the ambiance of [lighting condition] during [time and weather conditions].",
    "Amidst [time and weather conditions], the intriguing [scene type] encompasses [objects in the image and their quantity] under [lighting condition].",
    "During [time and weather conditions], [objects in the image and their quantity] stand out in the [lighting condition] against the [scene type].",
    "The [scene type] appears captivating with [objects in the image and their quantity] under [lighting condition] during [time and weather conditions].",
    "The [scene type] resonates with [objects in the image and their quantity] under [lighting condition] during an usual [time and weather conditions].",
    "The picturesque view of [scene type] shows [objects in the image and their quantity] amidst [lighting condition] during [time and weather conditions].",
    "Bursting with activity, the [scene type] spotlights [objects in the image and their quantity] in [lighting condition] during [time and weather conditions].",
    "The [scene type] under [time and weather conditions] presents a kaleidoscope of [objects in the image and their quantity] in [lighting condition].",
    "An eclectic mix of [objects in the image and their quantity] is set against the [lighting condition] of [scene type] during [time and weather conditions].",
    "The [scene type] under [lighting condition] beautifully brings out [objects in the image and their quantity] during [time and weather conditions].",
    "The [scene type] is adorned with [objects in the image and their quantity] under [lighting condition] against the backdrop of [time and weather conditions].",
    "The [scene type] caught in [lighting condition] reveals [objects in the image and their quantity] during a [time and weather conditions].",
    "The [scene type] in [lighting condition] frames [objects in the image and their quantity] set against a backdrop of [time and weather conditions].",
    "Amid [time and weather conditions], the [scene type] spotlights [objects in the image and their quantity] in [lighting condition].",
    "The [scene type], under [lighting condition] unveils [objects in the image and their quantity] with [time and weather conditions] setting the background.",
    "With [lighting condition] overhead, the [scene type] captures [objects in the image and their quantity] during [time and weather conditions].",
    "The tableau of [scene type] under [lighting condition] outlines [objects in the image and their quantity] amidst [time and weather conditions].",
    "The [scene type] in [lighting condition] vividly captures [objects in the image and their quantity] during [time and weather conditions].",
    "The [scene type] under [time and weather conditions] casts [objects in the image and their quantity] in [lighting condition].",
    "In perfect [lighting condition], the [scene type] comes alive with [objects in the image and their quantity] during [time and weather conditions].",
    "The indelible image of the [scene type] under [lighting condition] captures [objects in the image and their quantity] during [time and weather conditions].",
    "The vivacious [scene type] under [lighting condition] houses [objects in the image and their quantity] amidst the [time and weather conditions].",
    "Painted in [lighting condition], the [scene type] presents [objects in the image and their quantity] amidst [time and weather conditions].",
    "The [scene type] is a medley of [objects in the image and their quantity] under [lighting condition] during [time and weather conditions].",
    "The [scene type] under [time and weather conditions] is augmented by [objects in the image and their quantity] in the [lighting condition].",
    "The [scene type] basks in the [lighting condition], showcasing [objects in the image and their quantity] under the [time and weather conditions]."
]
if __name__ == '__main__':
    print(len(SENTENCE_TEMPLATE))